# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 01:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('currentlyDraft', models.BooleanField()),
                ('active', models.BooleanField()),
                ('lastEditedDate', models.DateTimeField()),
                ('recordDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('deepDive', models.TextField(blank=True)),
                ('active', models.BooleanField()),
                ('lastEditedDate', models.DateTimeField()),
                ('recordDate', models.DateTimeField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.List')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.DateTimeField()),
                ('degrees', models.CharField(blank=True, max_length=100)),
                ('jobTitle', models.CharField(blank=True, max_length=100)),
                ('personalDescription', models.TextField(blank=True)),
                ('favoriteLists', models.ManyToManyField(blank=True, related_name='favorites', to='lists.List')),
                ('friends', models.ManyToManyField(related_name='_person_friends_+', to='lists.Person')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recordDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.DateTimeField()),
                ('expirationDate', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('editPower', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.SubscriberGroup')),
            ],
        ),
        migrations.CreateModel(
            name='TopicTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestors', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('name', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('recordDate', models.DateTimeField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.TopicTree')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.TopicTree'),
        ),
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, to='lists.SubscriberGroup'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='list',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.TopicTree'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='listitem',
            order_with_respect_to='list',
        ),
    ]
